# Generated by Django 5.0.6 on 2024-06-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carrer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="jobs",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
