# Generated by Django 5.0.6 on 2024-06-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carrer", "0004_testimonial_image_testimonial_job_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestudy",
            name="short_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/images/testimonials/"
            ),
        ),
    ]
