# Generated by Django 5.0.6 on 2024-06-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carrer", "0005_casestudy_short_description_alter_testimonial_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
    ]
