# Generated by Django 5.0.6 on 2024-06-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carrer", "0008_remove_service_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MainCaseStudy",
        ),
        migrations.AddField(
            model_name="casestudy",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/images/case_study/"
            ),
        ),
    ]
