# Generated by Django 5.0.6 on 2024-06-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carrer", "0009_delete_maincasestudy_casestudy_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestudy",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="case_study/"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="testimonials/"),
        ),
    ]
