# Generated by Django 5.0.6 on 2024-06-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carrer", "0010_alter_casestudy_image_alter_testimonial_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("content", models.TextField()),
                ("category", models.CharField(max_length=50)),
                ("headline_image", models.ImageField(upload_to="articles/")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
