# Generated by Django 5.0.6 on 2024-06-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carrer", "0011_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("TECH BLOGS", "Tech Blogs"),
                    ("TECH NEWS", "Tech News"),
                    ("INDUSTRY UPDATES", "Industry Updates"),
                ],
                default="TECH BLOGS",
                max_length=50,
            ),
        ),
    ]
