# Generated by Django 5.0.6 on 2024-06-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carrer", "0012_alter_article_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("linkedin_profile", models.URLField(blank=True)),
                ("about", models.TextField()),
            ],
        ),
    ]
