# Generated by Django 5.0.6 on 2024-06-20 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carrer", "0017_casestudy_short_desc"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Service",
        ),
    ]
